// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8MttaaD1Lt2yEeHvNF6lfK-MVP_5ra0E',
    appId: '1:145429771633:web:5ece1d657d7485acefb2d0',
    messagingSenderId: '145429771633',
    projectId: 'testproject-96f2f',
    authDomain: 'testproject-96f2f.firebaseapp.com',
    storageBucket: 'testproject-96f2f.appspot.com',
    measurementId: 'G-DGL9HYBELN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl77FgVlzQxYmlXDs6cjUVUt_VyBf20_I',
    appId: '1:145429771633:android:5dab3e9918946c79efb2d0',
    messagingSenderId: '145429771633',
    projectId: 'testproject-96f2f',
    storageBucket: 'testproject-96f2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvYQDIZ_X8kwR2uWOXyBvctt77vI6lJ_4',
    appId: '1:145429771633:ios:125e06b77fe36ca3efb2d0',
    messagingSenderId: '145429771633',
    projectId: 'testproject-96f2f',
    storageBucket: 'testproject-96f2f.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8MttaaD1Lt2yEeHvNF6lfK-MVP_5ra0E',
    appId: '1:145429771633:web:e335a140ca94d3c3efb2d0',
    messagingSenderId: '145429771633',
    projectId: 'testproject-96f2f',
    authDomain: 'testproject-96f2f.firebaseapp.com',
    storageBucket: 'testproject-96f2f.appspot.com',
    measurementId: 'G-08YH1J4LWL',
  );

}